name: common
publish_to: "none"

environment:
  sdk: ^3.2.0

dependencies:
  get_it: ^7.6.4
  graphql: ^5.1.3
  meta: any

dev_dependencies:
  build_runner: ^2.4.6
  graphql_codegen: ^0.13.8
  test: ^1.24.9
