version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/app/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/app/packages/authentication_repository"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/services/analytics_service"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/common"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/common_ui"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/schemas"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/app/packages/storage/storage"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/storage/secure_storage"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/app/packages/services/remote_config"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/storybook/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
