version: 2
updates:
  # Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Root
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # App
  - package-ecosystem: "pub"
    directory: "/app/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Packages
  - package-ecosystem: "pub"
    directory: "/app/packages/common"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/common_data"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/common_ui"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/formz_inputs"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/schemas"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Services
  - package-ecosystem: "pub"
    directory: "/app/packages/services/analytics"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/services/crash_report"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/services/remote_config"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/services/storage/storage"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/app/packages/services/storage/secure_storage"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pub"
    directory: "/storybook/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
