version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/storybook/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/packages/authentication_repository"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/packages/user_repository"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/packages/analytics_repository"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/packages/common_ui"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
