version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - ":package: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
