name: quickstart_flutter_bloc

packages:
  - app
  - app/packages/*
  - app/packages/services/*
  - app/packages/services/storage/*
  - storybook

command:
  bootstrap:
    hooks:
      pre: melos hooks && cp .env.example .env.development

scripts:
  # Flutter commands
  get:
    exec: flutter pub get
    description: Get all dependencies.

  upgrade:
    exec: flutter pub upgrade
    description: Upgrade all dependencies.

  lint:
    run: melos format:no-output && melos analyze
    description: Lint all packages.

  analyze:
    exec: flutter analyze
    description: Analyze all packages.

  format:
    exec: dart format .
    description: Format all packages.

  format:no-output:
    exec: dart format --output none --set-exit-if-changed .
    description: Run `dart format` for all packages and fail if any files need to be formatted.

  test:
    run: melos test:single --no-select
    description: Run all tests available.

  test:single:
    exec: flutter test
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test

  # App commands
  l10n:
    exec: dart run slang && dart format lib/l10n/translations.g.dart
    description: Generate localization files.
    packageFilters:
      scope:
        - quickstart_flutter_bloc

  l10n:analyze:
    exec: dart run slang analyze --full --exit-if-changed
    description: Analyze localization files.
    packageFilters:
      scope: quickstart_flutter_bloc

  gen:
    run: melos gen:single --no-select
    description: Run build_runner in all packages.

  gen:single:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner to generate files.
    packageFilters:
      dependsOn: build_runner

  splash_screen:
    exec: flutter pub run flutter_native_splash:create
    description: Update the app splash screen.
    packageFilters:
      scope: quickstart_flutter_bloc

  launcher_icon:
    exec: flutter pub run flutter_launcher_icons:main
    description: Update the app launcher icon.
    packageFilters:
      scope: quickstart_flutter_bloc

  build:android-dev:
    exec: flutter build appbundle --flavor development --dart-define-from-file ../.env.development
    description: (DEV) Build the Android app.
    packageFilters:
      scope:
        - quickstart_flutter_bloc

  build:android-prd:
    exec: flutter build appbundle --flavor production --dart-define-from-file ../.env.production
    description: (PRD) Build the Android app.
    packageFilters:
      scope:
        - quickstart_flutter_bloc

  # Git commands
  hooks:
    run: dart run husky install
    description: Install git hooks.

ide:
  intellij:
    enabled: false
