name: quickstart_flutter_bloc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analytics_repository:
    path: ./packages/analytics_repository
  authentication_repository:
    path: ./packages/authentication_repository
  common_ui:
    path: ./packages/common_ui
  equatable: ^2.0.5
  firebase_analytics: ^10.7.0
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_performance: ^0.9.3+4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  formz: ^0.6.1
  formz_inputs: ^1.1.1
  go_router: ^12.1.1
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  path_provider: ^2.1.1
  pinput: ^3.0.1
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  user_repository:
    path: ./packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  melos: ^3.2.0

flutter:
  uses-material-design: true
