name: flutter_bloc_starter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analytics_repository:
    path: ./packages/analytics_repository
  authentication_repository:
    path: ./packages/authentication_repository
  cached_network_image: ^3.3.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_messaging: ^14.6.9
  firebase_performance: ^0.9.2+7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_svg: ^2.0.7
  formz: ^0.6.1
  formz_inputs: ^1.1.1
  go_router: ^11.1.4
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  path_provider: ^2.1.1
  pinput: ^3.0.1
  user_repository:
    path: ./packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
