name: flutter_bloc_starter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_performance: ^0.9.2+4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  formz: ^0.6.0
  formz_inputs: ^1.0.0
  go_router: ^10.0.0
  intl: ^0.18.0
  pinput: ^2.2.31
  sign_in_button: ^3.2.0

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  generate: true
  uses-material-design: true
