name: flutter_bloc_starter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.2
  firebase_performance: ^0.9.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  go_router: ^7.0.0
  intl: ^0.17.0
  pinput: ^2.2.31

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  generate: true
  uses-material-design: true
