#!/bin/bash
set -e

SELF=$(basename "$0")
HOOKS_DIR=$(dirname "$PWD"/"$0")
GIT_COMMON_DIR=$(git rev-parse --show-toplevel)/.git

if [ ! -d "$GIT_COMMON_DIR/hooks" ]; then
    mkdir -p "$GIT_COMMON_DIR/hooks"
fi

for F in "$HOOKS_DIR"/*; do
    HOOK_NAME=$(basename "$F")
    if [ "$SELF" != "$HOOK_NAME" ] && [ -x "$F" ]; then
        echo "Installing $HOOK_NAME in $GIT_COMMON_DIR/hooks/$HOOK_NAME"
        ln -sf "$F" "$GIT_COMMON_DIR/hooks/$HOOK_NAME"
    fi
done
