name: analytics_service
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  firebase_analytics: ^10.7.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
