targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          namingSeparator: ""
          outputDirectory: generated
          scalars:
            DateTime:
              type: DateTime
            JSONObject:
              type: Map<String, dynamic>
