name: quickstart_flutter_bloc
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analytics_service:
    path: ./packages/analytics_service
  auto_route: ^8.0.3
  common:
    path: ./packages/common
  common_ui:
    path: ./packages/common_ui
  equatable: ^2.0.5
  firebase_core: ^2.28.0
  firebase_crashlytics: ^3.5.0
  firebase_performance: ^0.9.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  formz_inputs:
    path: ./packages/formz_inputs
  gap: ^3.0.1
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2
  schemas:
    path: ./packages/schemas
  secure_storage:
    path: ./packages/storage/secure_storage
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  storage:
    path: ./packages/storage/storage

dev_dependencies:
  auto_route_generator: ^8.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
