name: quickstart_flutter_bloc
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  analytics_service:
    path: ./packages/analytics_service
  authentication_repository:
    path: ./packages/authentication_repository
  auto_route: ^7.8.4
  common:
    path: ./packages/common
  common_ui:
    path: ./packages/common_ui
  equatable: ^2.0.5
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.5
  firebase_performance: ^0.9.3+5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.6.1
  formz_inputs: ^1.1.1
  gap: ^3.0.1
  graphql: ^5.1.3
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  slang: ^3.25.0
  slang_flutter: ^3.25.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
