name: flutter_bloc_starter
publish_to: "none"
version: 0.1.1+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analytics_service:
    path: ./packages/services/analytics
  auto_route: ^8.3.0
  biometric_service:
    path: ./packages/services/biometric
  common:
    path: ./packages/common
  common_data:
    path: ./packages/common_data
  common_ui:
    path: ./packages/common_ui
  crash_report_service:
    path: ./packages/services/crash_report
  equatable: ^2.0.5
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  formz_inputs:
    path: ./packages/formz_inputs
  persistent_storage_service:
    path: ./packages/services/persistent_storage
  remote_config_service:
    path: ./packages/services/remote_config
  schemas:
    path: ./packages/schemas
  secure_storage_service:
    path: ./packages/services/secure_storage
  slang: ^3.31.1
  slang_flutter: ^3.31.0

dev_dependencies:
  auto_route_generator: ^8.1.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
