name: common_ui
publish_to: "none"

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/logos/
