name: common_data
publish_to: "none"

environment:
  sdk: ^3.4.0

dependencies:
  common:
    path: ../common
  dio: ^5.4.3+1
  graphql: ^5.1.3
  graphql_query_compress: ^1.0.0
  storage_service:
    path: ../services/storage/storage
