name: Auto Tag

on:
  workflow_run:
    workflows: [Code Check]
    types:
      - completed
    branches:
      - main

jobs:
  auto-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto Tag when the pubspec.yaml version changes
        uses: jacopocarlini/action-autotag@3.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          tag_prefix: "v"
          package_root: /app
