name: Code Check

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-commits-authors:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    if: github.event.pull_request.draft == false || github.event_name == 'push'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: profusion/check-pr-commits-authors-action@main
        with:
          EMAIL_PATTERN: ^.*@profusion\.mobi$
          IGNORED_EMAIL_PATTERN: ^.*dependabot\[bot\]@users\.noreply\.github\.com # ignore dependabot

  test:
    needs: check-commits-authors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - uses: bluefireteam/melos-action@v3

      - name: Run Flutter Test
        run: melos test

  lint:
    needs: check-commits-authors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"

      - uses: bluefireteam/melos-action@v3

      - name: Run Flutter Format
        run: melos format:no-output

      - name: Run Flutter Analyze
        run: melos analyze

      - name: Analyze Localizations
        run: melos l10n:analyze
