name: Code Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ricardodalarme/bump-pubspec-version@main
        with:
          mode: "major" # major, minor, patch
          github_token: ${{ secrets.GITHUB_TOKEN }}
