name: Deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"

      - name: Build Android appbundle
        run: melos build:android-dev
