name: common_ui
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/logos/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/

  integrations:
    flutter_svg: true
